apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: sensors
  DB_USER: sensors
  DB_PASSWORD: sensors
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
